### ISSUE TITLE
Keep a space between - and start of number in total cases.

### ISSUE THREAD

**Issue by co-learning-lounge** [krngd2/CovidWithD3js#12]
Issues to fix @ https://covidwithd3js.kiran.dev/indiamap/

1. Total cases - |space| 123
2. Add color range legend at the bottom.
3. Show three in the respective color.
Orange - Total cases
Green - Recovered
Red - Total deaths
![image](https://user-images.githubusercontent.com/51528654/83976143-da4b5980-a915-11ea-8333-d5b1d0d535b2.png)

**Comment by krngd2** [comment]
@lokeshkotha Take up 3, 1 and 2 are done

**Comment by co-learning-lounge** [comment]
Did we change the range?
I just asked to keep the color range legend.

The current range is really poor. ~10,000 cases still that area is not Red
![image](https://user-images.githubusercontent.com/51528654/84018147-5472f100-a99d-11ea-8e6d-6091521a5d23.png)

Reference 1:
![image](https://user-images.githubusercontent.com/51528654/84018237-6f456580-a99d-11ea-867c-12c66bfcb584.png)

Refernece 2:
![image](https://user-images.githubusercontent.com/51528654/84018250-73718300-a99d-11ea-899b-3d1a9ea52ebd.png)

**Comment by lokeshkotha** [comment]
Completed
