### ISSUE TITLE
Add a Total cases, Recovered, Total deaths, Countries

### ISSUE THREAD

**Issue by co-learning-lounge** [krngd2/CovidWithD3js#13]
Enhancement to add @ https://covidwithd3js.kiran.dev/barchartrace/

1. Show three in the respective color.
Orange - Total cases
Green - Recovered
Red - Total deaths
Countries
![image](https://user-images.githubusercontent.com/51528654/83976401-4b3f4100-a917-11ea-80e9-b2a8971933f8.png)

**Comment by dhruvkp090** [comment]
Fixed it in the f7e6f21ad9e3161b6bbff61a1c137342aabfdf9f commit. Check it out
